# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-06 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('staff_id', models.CharField(max_length=10)),
                ('position', models.CharField(choices=[('GM', 'AEDC3-General Manager'), ('SM', 'AEDC3-Senior Manager'), ('M', 'AEDC5-Manager'), ('AM', 'AEDC6-Assistant Manager'), ('SO', 'AEDC7-Senior Officer'), ('FO1', 'AEDC8-Function Officer 1'), ('FO2', 'AEDC-9-Function Officer 2'), ('SUO', 'AEDC-10-Support Officer')], max_length=1)),
            ],
        ),
    ]
