# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-08 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalsetting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='goal_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.TextField(max_length=300)),
                ('specific_task', models.TextField(max_length=300)),
                ('KPI', models.TextField(max_length=300)),
                ('Strategic_focus', models.CharField(choices=[('AT&C', 'Reduce ATC&C Loss'), ('ACV', 'Achieve Financial Viability'), ('CCCO', 'Create Customer Centric Organization'), ('ERSES', 'Effective Regulatory & Stakeholders Engagement Strategies'), ('IPAMP', 'Implement Prudent Asset Management Practices'), ('ECCT', 'Ensure Complete Corporate Transformation'), ('CHPC', 'Create High Performance Culture')], max_length=1)),
                ('weight', models.IntegerField()),
                ('timeline', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='period_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='goal_form',
            name='appraisee_comment',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='goal_form',
            name='appraisee_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='goal_form',
            name='appraiser_comment',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='goal_form',
            name='appraiser_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='goal_form',
            name='area_office',
            field=models.CharField(choices=[('gwag', 'Gwagwalada'), ('jabi', 'Jabi'), ('kuje', 'Kuje'), ('lokog', 'Lokogoma'), ('aso', 'Asokoro'), ('garki', 'Garki'), ('jikwoyi', 'Jikwoyi'), ('karu', 'Karu'), ('maitama', 'Maitama'), ('wuse', 'Wuse'), ('bwari', 'Bwari'), ('gwarinpa', 'Gwarinpa'), ('katampe', 'Katampe'), ('kubwa', 'Kubwa'), ('life', 'Life Camp'), ('bida', 'Bida'), ('bosso', 'Bosso'), ('kotangora', 'Kotangora'), ('minna', 'Minna'), ('suleja', 'Suleja'), ('zuma', 'Zuma'), ('idah', 'Idah'), ('kabba', 'Kabba'), ('lokoja', 'Lokoja'), ('okene', 'Okene'), ('ado', 'Ado'), ('akwanga', 'Akwanga'), ('keffi', 'Keffi'), ('lafia', 'Lafia'), ('mararaba', 'Mararaba')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='goal_form',
            name='designation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='goal_form',
            name='directorate',
            field=models.CharField(choices=[('CMPMO', 'Change Management and PMO'), ('commercial', 'Commercial Services'), ('cs', 'Corporate Services'), ('fs', 'Financial Services'), ('ict', 'Information Communication and Technology'), ('audit', 'Internal Audit'), ('legal', 'Legal Services and Company Secretariat'), ('risk', 'Risk and Compliance'), ('technical', 'Technical')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='goal_form',
            name='reviewer',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='goal_form',
            name='reviewer_comment',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='goal_form',
            name='supervisor_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='goal_form',
            name='unit',
            field=models.CharField(choices=[('change', 'AEDC Change'), ('billing', 'Billing'), ('corp risk', 'Business Corporate Risk'), ('comm perf', 'Commercial Performance Management'), ('comms facilities', 'Communications Facilities and Infrastructure'), ('legal', 'Company Secretariat'), ('comp audit', 'Compliance Audit'), ('contract', 'Contract and Documentation'), ('corp comms', 'Corporate Communications'), ('corp finance', 'Corporate Finance and Corporate Development'), ('ccu', 'Customer Care Services'), ('cyber sec', 'Cyber Security and BCP'), ('dispute', 'Dispute Resolution'), ('Env and social', 'Environmental and Social'), ('fin ops', 'Financial Operations'), ('fleet', 'Fleet Management and Logistics'), ('GIS', 'GIS and Communications'), ('HSE', 'Health and Safety'), ('hr', 'Human Resources and Administration'), ('IT audit', 'IT Audit'), ('key/debt', 'Key/Debt Account'), ('Legal adv', 'Legal Advisory'), ('Legal serv', 'Legal Services'), ('ceo', 'Management Office'), ('Net Dev', 'Network Development'), ('Net Ops', 'Network Operations'), ('ops and maintenance', 'Operations and Maintenance'), ('ops audit', 'Operations Audit'), ('ops control', 'Operations Control'), ('PCC', 'Protetion, Control and Communincations'), ('QA', 'Quality Assurance'), ('rem', 'Real Estate Management'), ('rgr', 'Regulatory and Government Relations'), ('rpu', 'Revenue Protection'), ('ss', 'Security Services'), ('spmo', 'Strategic PMO Office'), ('scp', 'Strategic and Corporate Planning'), ('sc', 'Supply Chain (Procurement)'), ('tfrm', 'Treasury and Financial Risk Management'), ('usam', 'User Support and Application Management'), ('vend', 'Vending')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='goal_form',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='goal_form',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='goal_form',
            name='middle_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='goal_form',
            name='position',
            field=models.CharField(choices=[('GM', 'AEDC3-General Manager'), ('SM', 'AEDC3-Senior Manager'), ('M', 'AEDC5-Manager'), ('AM', 'AEDC6-Assistant Manager'), ('SO', 'AEDC7-Senior Officer'), ('FO1', 'AEDC8-Function Officer 1'), ('FO2', 'AEDC-9-Function Officer 2'), ('SUO', 'AEDC-10-Support Officer')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='goal_form',
            name='staff_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
