# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-08 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalsetting', '0002_auto_20190808_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal_form',
            name='region',
            field=models.CharField(choices=[('central', 'FCT Central'), ('north', 'FCT North'), ('south', 'FCT South'), ('kogi', 'Kogi'), ('niger', 'Niger'), ('nassarawa', 'Nassarawa')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='goal_info',
            name='Balanced_scorecard',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
