# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-08 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goalsetting', '0003_auto_20190808_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal_form',
            old_name='reviewer',
            new_name='reviewer_email',
        ),
    ]
