# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-08 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goalsetting', '0004_auto_20190808_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal_info',
            name='Balanced_scorecard',
        ),
    ]
