# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-08 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalsetting', '0005_remove_goal_info_balanced_scorecard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period_info',
            name='date_from',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='period_info',
            name='date_to',
            field=models.CharField(max_length=50),
        ),
    ]
