# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-08 22:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goalsetting', '0007_auto_20190808_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_from', models.CharField(max_length=50, null=True)),
                ('period_to', models.CharField(max_length=50, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='goal_form',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goal_info',
            name='period_from',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='goal_info',
            name='period_to',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='goal_info',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
