# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-12 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalsetting', '0008_auto_20190808_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal_info',
            name='Strategic_focus',
            field=models.CharField(choices=[('AT&C', 'Reduce ATC&C Loss'), ('ACV', 'Achieve Financial Viability'), ('CCCO', 'Create Customer Centric Organization'), ('ERSES', 'Effective Regulatory & Stakeholders Engagement Strategies'), ('IPAMP', 'Implement Prudent Asset Management Practices'), ('ECCT', 'Ensure Complete Corporate Transformation'), ('CHPC', 'Create High Performance Culture')], max_length=90),
        ),
    ]
