# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-12 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalsetting', '0009_auto_20190812_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal_info',
            name='Balanced_scorecard',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
