# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-26 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalsetting', '0014_remove_goal_form_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal_info',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
