# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-26 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalsetting', '0015_auto_20190926_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal_form',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goal_form',
            name='area_office',
            field=models.CharField(choices=[('Gwagwalada', 'Gwagwalada'), ('Jabi', 'Jabi'), ('Kuje', 'Kuje'), ('Lokogoma', 'Lokogoma'), ('Asokoro', 'Asokoro'), ('Garki', 'Garki'), ('Jikwoyi', 'Jikwoyi'), ('Karu', 'Karu'), ('Maitama', 'Maitama'), ('Wuse', 'Wuse'), ('Bwari', 'Bwari'), ('Gwarinpa', 'Gwarinpa'), ('Katampe', 'Katampe'), ('Kubwa', 'Kubwa'), ('Life Camp', 'Life Camp'), ('Bida', 'Bida'), ('Bosso', 'Bosso'), ('Kotangora', 'Kotangora'), ('Minna', 'Minna'), ('Suleja', 'Suleja'), ('Zuma', 'Zuma'), ('Idah', 'Idah'), ('Kabba', 'Kabba'), ('Lokoja', 'Lokoja'), ('Okene', 'Okene'), ('Ado', 'Ado'), ('Akwanga', 'Akwanga'), ('Keffi', 'Keffi'), ('Lafia', 'Lafia'), ('Mararaba', 'Mararaba')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='goal_form',
            name='directorate',
            field=models.CharField(choices=[('Change Management and PMO', 'Change Management and PMO'), ('Commercial Services', 'Commercial Services'), ('Corporate Services', 'Corporate Services'), ('Financial Services', 'Financial Services'), ('Information Communication and Technology', 'Information Communication and Technology'), ('Internal Audit', 'Internal Audit'), ('Legal Services and Company Secretariat', 'Legal Services and Company Secretariat'), ('Risk and Compliance', 'Risk and Compliance'), ('Technical', 'Technical')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='goal_form',
            name='position',
            field=models.CharField(choices=[('AEDC3-General Manager', 'AEDC3-General Manager'), ('AEDC4-Senior Manager', 'AEDC4-Senior Manager'), ('AEDC5-Manager', 'AEDC5-Manager'), ('AEDC6-Assistant Manager', 'AEDC6-Assistant Manager'), ('AEDC7-Senior Officer', 'AEDC7-Senior Officer'), ('AEDC8-Function Officer 1', 'AEDC8-Function Officer 1'), ('AEDC-9-Function Officer 2', 'AEDC-9-Function Officer 2'), ('AEDC-10-Support Officer', 'AEDC-10-Support Officer')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='goal_form',
            name='region',
            field=models.CharField(choices=[('FCT Central', 'FCT Central'), ('FCT North', 'FCT North'), ('FCT South', 'FCT South'), ('Kogi', 'Kogi'), ('Niger', 'Niger'), ('Nassarawa', 'Nassarawa')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='goal_form',
            name='unit',
            field=models.CharField(choices=[('AEDC Change', 'AEDC Change'), ('Billing', 'Billing'), ('Business Corporate Risk', 'Business Corporate Risk'), ('Commercial Performance Management', 'Commercial Performance Management'), ('Communications Facilities and Infrastructure', 'Communications Facilities and Infrastructure'), ('Company Secretariat', 'Company Secretariat'), ('Compliance Audit', 'Compliance Audit'), ('Contract and Documentation', 'Contract and Documentation'), ('Corporate Communications', 'Corporate Communications'), ('Corporate Finance and Corporate Development', 'Corporate Finance and Corporate Development'), ('Customer Care Services', 'Customer Care Services'), ('Cyber Security and BCP', 'Cyber Security and BCP'), ('Dispute Resolution', 'Dispute Resolution'), ('Environmental and Social', 'Environmental and Social'), ('Financial Operations', 'Financial Operations'), ('Fleet Management and Logistics', 'Fleet Management and Logistics'), ('GIS and Communications', 'GIS and Communications'), ('Health and Safety', 'Health and Safety'), ('Human Resources and Administration', 'Human Resources and Administration'), ('IT Audit', 'IT Audit'), ('Key/Debt Account', 'Key/Debt Account'), ('Legal Advisory', 'Legal Advisory'), ('Legal Services', 'Legal Services'), ('Management Office', 'Management Office'), ('Network Development', 'Network Development'), ('Network Surveillance', 'Network Surveillance'), ('Network Operations', 'Network Operations'), ('Operations and Maintenance', 'Operations and Maintenance'), ('Operations Audit', 'Operations Audit'), ('Operations Control', 'Operations Control'), ('Protection, Control and Communications', 'Protection, Control and Communications'), ('Quality Assurance', 'Quality Assurance'), ('Real Estate Management', 'Real Estate Management'), ('Regulatory and Government Relations', 'Regulatory and Government Relations'), ('Revenue Protection', 'Revenue Protection'), ('Security Services', 'Security Services'), ('Strategic PMO Office', 'Strategic PMO Office'), ('Strategic and Corporate Planning', 'Strategic and Corporate Planning'), ('Supply Chain (Procurement)', 'Supply Chain (Procurement)'), ('Treasury and Financial Risk Management', 'Treasury and Financial Risk Management'), ('User Support and Application Management', 'User Support and Application Management'), ('Vending', 'Vending')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='goal_info',
            name='Strategic_focus',
            field=models.CharField(choices=[('Reduce ATC&C Loss', 'Reduce ATC&C Loss'), ('Achieve Financial Viability', 'Achieve Financial Viability'), ('Create Customer Centric Organization', 'Create Customer Centric Organization'), ('Effective Regulatory & Stakeholders Engagement Strategies', 'Effective Regulatory & Stakeholders Engagement Strategies'), ('Implement Prudent Asset Management Practices', 'Implement Prudent Asset Management Practices'), ('Ensure Complete Corporate Transformation', 'Ensure Complete Corporate Transformation'), ('Create High Performance Culture', 'Create High Performance Culture')], max_length=90),
        ),
    ]
