# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-13 14:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goalsetting', '0016_auto_20190926_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('staff_id', models.CharField(max_length=10, null=True)),
                ('period_from', models.CharField(max_length=50, null=True)),
                ('period_to', models.CharField(max_length=50, null=True)),
                ('appraisee_comment', models.TextField(blank=True, max_length=300, null=True)),
                ('appraiser_comment', models.TextField(blank=True, max_length=300, null=True)),
                ('reviewer_comment', models.TextField(blank=True, max_length=300, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='goal_form',
            name='appraisee_comment',
        ),
        migrations.RemoveField(
            model_name='goal_form',
            name='appraiser_comment',
        ),
        migrations.RemoveField(
            model_name='goal_form',
            name='reviewer_comment',
        ),
        migrations.AlterField(
            model_name='goal_form',
            name='area_office',
            field=models.CharField(choices=[('Gwagwalada', 'Gwagwalada'), ('Jabi', 'Jabi'), ('Kuje', 'Kuje'), ('Lokogoma', 'Lokogoma'), ('Asokoro', 'Asokoro'), ('Garki', 'Garki'), ('Jikwoyi', 'Jikwoyi'), ('Karu', 'Karu'), ('Maitama', 'Maitama'), ('Head Office', 'Head Office'), ('Wuse', 'Wuse'), ('Bwari', 'Bwari'), ('Gwarinpa', 'Gwarinpa'), ('Katampe', 'Katampe'), ('Kubwa', 'Kubwa'), ('Life Camp', 'Life Camp'), ('Bida', 'Bida'), ('Bosso', 'Bosso'), ('Kotangora', 'Kotangora'), ('Minna', 'Minna'), ('Suleja', 'Suleja'), ('Zuma', 'Zuma'), ('Idah', 'Idah'), ('Kabba', 'Kabba'), ('Lokoja', 'Lokoja'), ('Okene', 'Okene'), ('Ado', 'Ado'), ('Akwanga', 'Akwanga'), ('Keffi', 'Keffi'), ('Lafia', 'Lafia'), ('Mararaba', 'Mararaba')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='goal_form',
            name='region',
            field=models.CharField(choices=[('FCT Central', 'FCT Central'), ('FCT North', 'FCT North'), ('FCT South', 'FCT South'), ('FCT West', 'FCT West'), ('FCT East', 'FCT East'), ('Head Office', 'Head Office'), ('Kogi', 'Kogi'), ('Niger', 'Niger'), ('Nassarawa', 'Nassarawa')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='goal_form',
            name='unit',
            field=models.CharField(choices=[('AEDC Change', 'AEDC Change'), ('Billing', 'Billing'), ('Billing', 'Billing'), ('Fraud Billing', 'Fraud Billing'), ('Technical Services', 'Technical Services'), ('Commercial Services', 'Commercial Services'), ('MAP', 'MAP'), ('SPM', 'SPM'), ('Projects', 'Projects'), ('Protocol', 'Protocol'), ('Business Corporate Risk', 'Business Corporate Risk'), ('Commercial Performance Management', 'Commercial Performance Management'), ('Communications Facilities and Infrastructure', 'Communications Facilities and Infrastructure'), ('Company Secretariat', 'Company Secretariat'), ('Compliance Audit', 'Compliance Audit'), ('Contract and Documentation', 'Contract and Documentation'), ('Corporate Communications', 'Corporate Communications'), ('Corporate Finance and Corporate Development', 'Corporate Finance and Corporate Development'), ('Customer Care Services', 'Customer Care Services'), ('Cyber Security and BCP', 'Cyber Security and BCP'), ('Dispute Resolution', 'Dispute Resolution'), ('Environmental and Social', 'Environmental and Social'), ('Financial Operations', 'Financial Operations'), ('Fleet Management and Logistics', 'Fleet Management and Logistics'), ('GIS and Communications', 'GIS and Communications'), ('Health and Safety', 'Health and Safety'), ('Human Resources and Administration', 'Human Resources and Administration'), ('IT Audit', 'IT Audit'), ('Key/Debt Account', 'Key/Debt Account'), ('Legal Advisory', 'Legal Advisory'), ('Legal Services', 'Legal Services'), ('Management Office', 'Management Office'), ('Network Development', 'Network Development'), ('Network Surveillance', 'Network Surveillance'), ('Network Operations', 'Network Operations'), ('Operations and Maintenance', 'Operations and Maintenance'), ('Operations Audit', 'Operations Audit'), ('Operations Control', 'Operations Control'), ('Protection, Control and Communications', 'Protection, Control and Communications'), ('Quality Assurance', 'Quality Assurance'), ('Real Estate Management', 'Real Estate Management'), ('Regulatory and Government Relations', 'Regulatory and Government Relations'), ('Revenue Protection', 'Revenue Protection'), ('Security Services', 'Security Services'), ('Strategic PMO Office', 'Strategic PMO Office'), ('Strategic and Corporate Planning', 'Strategic and Corporate Planning'), ('Supply Chain (Procurement)', 'Supply Chain (Procurement)'), ('Treasury and Financial Risk Management', 'Treasury and Financial Risk Management'), ('User Support and Application Management', 'User Support and Application Management'), ('Vending', 'Vending')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='goal_info',
            name='Strategic_focus',
            field=models.CharField(choices=[('Reduce ATC&C Loss', 'Reduce ATC&C Loss'), ('Achieve Financial Viability', 'Achieve Financial Viability'), ('Create a Customer Centric Organization', 'Create a Customer Centric Organization'), ('Effective Regulatory & Stakeholders Engagement', 'Effective Regulatory & Stakeholders Engagement'), ('Improve HSE Practices', 'Improve HSE Practices'), ('Implement Prudent Asset Management Practices', 'Implement Prudent Asset Management Practices'), ('Deploy Fit for Purpose ICT Business Solutions', 'Deploy Fit for Purpose ICT Business Solutions'), ('Create a High Performance Culture', 'Create a High Performance Culture'), ('Compliance with Reengineered Business Processes', 'Compliance with Reengineered Business Processes')], max_length=90),
        ),
    ]
