# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-27 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalsetting', '0018_auto_20191108_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal_form',
            name='unit',
            field=models.CharField(choices=[('AEDC Change', 'AEDC Change'), ('Billing', 'Billing'), ('Fraud Billing', 'Fraud Billing'), ('Debt Management', 'Debt Management'), ('Technical Services', 'Technical Services'), ('Commercial Services', 'Commercial Services'), ('MAP', 'MAP'), ('SPM', 'SPM'), ('Projects', 'Projects'), ('Protocol', 'Protocol'), ('Human Resources and Industrial Relations', 'Human Resources and Industrial Relations'), ('Business Corporate Risk', 'Business Corporate Risk'), ('Commercial Performance Management', 'Commercial Performance Management'), ('Communications Facilities and Infrastructure', 'Communications Facilities and Infrastructure'), ('Company Secretariat', 'Company Secretariat'), ('Compliance Audit', 'Compliance Audit'), ('Contract and Documentation', 'Contract and Documentation'), ('Corporate Communications', 'Corporate Communications'), ('Corporate Finance and Corporate Development', 'Corporate Finance and Corporate Development'), ('Customer Care Services', 'Customer Care Services'), ('Cyber Security and BCP', 'Cyber Security and BCP'), ('Dispute Resolution', 'Dispute Resolution'), ('Environmental and Social', 'Environmental and Social'), ('Financial Operations', 'Financial Operations'), ('Fleet Management and Logistics', 'Fleet Management and Logistics'), ('GIS and Communications', 'GIS and Communications'), ('Health and Safety', 'Health and Safety'), ('Human Resources and Administration', 'Human Resources and Administration'), ('IT Audit', 'IT Audit'), ('Key/Debt Account', 'Key/Debt Account'), ('Legal Advisory', 'Legal Advisory'), ('Legal Services', 'Legal Services'), ('Management Office', 'Management Office'), ('Network Deployment', 'Network Deployment'), ('Network Surveillance', 'Network Surveillance'), ('Network Operations', 'Network Operations'), ('Operations and Maintenance', 'Operations and Maintenance'), ('Operations Audit', 'Operations Audit'), ('Operations Control', 'Operations Control'), ('Protection, Control and Communications', 'Protection, Control and Communications'), ('Quality Assurance', 'Quality Assurance'), ('Facility', 'Facility'), ('Regulatory and Government Relations', 'Regulatory and Government Relations'), ('Revenue Protection', 'Revenue Protection'), ('Security Services', 'Security Services'), ('Shared Services', 'Shared Services'), ('Strategic PMO Office', 'Strategic PMO Office'), ('Strategic and Corporate Planning', 'Strategic and Corporate Planning'), ('Supply Chain (Procurement)', 'Supply Chain (Procurement)'), ('Treasury and Financial Risk Management', 'Treasury and Financial Risk Management'), ('User Support and Application Management', 'User Support and Application Management'), ('Vending', 'Vending'), ('ICT Infrastructure and Platform', 'ICT Infrastructure and Platform')], max_length=100, null=True),
        ),
    ]
