# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-27 12:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accomplishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_from', models.CharField(max_length=50, null=True)),
                ('period_to', models.CharField(max_length=50, null=True)),
                ('accomplishment', models.CharField(max_length=50, null=True)),
                ('business_impact', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appr_approve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_from', models.CharField(max_length=50, null=True)),
                ('period_to', models.CharField(max_length=50, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appr_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appr_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('staff_id', models.CharField(max_length=10, null=True)),
                ('period_from', models.CharField(max_length=50, null=True)),
                ('period_to', models.CharField(max_length=50, null=True)),
                ('appraisee_comment', models.TextField(blank=True, max_length=300, null=True)),
                ('appraiser_comment', models.TextField(blank=True, max_length=300, null=True)),
                ('reviewer_comment', models.TextField(blank=True, max_length=300, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appr_period_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.CharField(max_length=50)),
                ('date_to', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Appraisal_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('middle_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('staff_id', models.CharField(max_length=10, null=True)),
                ('position', models.CharField(choices=[('AEDC3-General Manager', 'AEDC3-General Manager'), ('AEDC4-Senior Manager', 'AEDC4-Senior Manager'), ('AEDC5-Manager', 'AEDC5-Manager'), ('AEDC6-Assistant Manager', 'AEDC6-Assistant Manager'), ('AEDC7-Senior Officer', 'AEDC7-Senior Officer'), ('AEDC8-Function Officer 1', 'AEDC8-Function Officer 1'), ('AEDC-9-Function Officer 2', 'AEDC-9-Function Officer 2'), ('AEDC-10-Support Officer', 'AEDC-10-Support Officer')], max_length=30, null=True)),
                ('unit', models.CharField(choices=[('AEDC Change', 'AEDC Change'), ('Billing', 'Billing'), ('Fraud Billing', 'Fraud Billing'), ('Debt Management', 'Debt Management'), ('Technical Services', 'Technical Services'), ('Commercial Services', 'Commercial Services'), ('MAP', 'MAP'), ('SPM', 'SPM'), ('Projects', 'Projects'), ('Protocol', 'Protocol'), ('Human Resources and Industrial Relations', 'Human Resources and Industrial Relations'), ('Business Corporate Risk', 'Business Corporate Risk'), ('Commercial Performance Management', 'Commercial Performance Management'), ('Communications Facilities and Infrastructure', 'Communications Facilities and Infrastructure'), ('Company Secretariat', 'Company Secretariat'), ('Compliance Audit', 'Compliance Audit'), ('Contract and Documentation', 'Contract and Documentation'), ('Corporate Communications', 'Corporate Communications'), ('Corporate Finance and Corporate Development', 'Corporate Finance and Corporate Development'), ('Customer Care Services', 'Customer Care Services'), ('Cyber Security and BCP', 'Cyber Security and BCP'), ('Dispute Resolution', 'Dispute Resolution'), ('Environmental and Social', 'Environmental and Social'), ('Financial Operations', 'Financial Operations'), ('Fleet Management and Logistics', 'Fleet Management and Logistics'), ('GIS and Communications', 'GIS and Communications'), ('Health and Safety', 'Health and Safety'), ('Human Resources and Administration', 'Human Resources and Administration'), ('IT Audit', 'IT Audit'), ('Key/Debt Account', 'Key/Debt Account'), ('Legal Advisory', 'Legal Advisory'), ('Legal Services', 'Legal Services'), ('Management Office', 'Management Office'), ('Network Deployment', 'Network Deployment'), ('Network Surveillance', 'Network Surveillance'), ('Network Operations', 'Network Operations'), ('Operations and Maintenance', 'Operations and Maintenance'), ('Operations Audit', 'Operations Audit'), ('Operations Control', 'Operations Control'), ('Protection, Control and Communications', 'Protection, Control and Communications'), ('Quality Assurance', 'Quality Assurance'), ('Facility', 'Facility'), ('Regulatory and Government Relations', 'Regulatory and Government Relations'), ('Revenue Protection', 'Revenue Protection'), ('Security Services', 'Security Services'), ('Shared Services', 'Shared Services'), ('Strategic PMO Office', 'Strategic PMO Office'), ('Strategic and Corporate Planning', 'Strategic and Corporate Planning'), ('Supply Chain (Procurement)', 'Supply Chain (Procurement)'), ('Treasury and Financial Risk Management', 'Treasury and Financial Risk Management'), ('User Support and Application Management', 'User Support and Application Management'), ('Vending', 'Vending'), ('ICT Infrastructure and Platform', ' ICT Infrastructure and Platform')], max_length=100, null=True)),
                ('directorate', models.CharField(choices=[('Change Management and PMO', 'Change Management and PMO'), ('Projects', 'Projects'), ('Corporate Services', 'Corporate Services'), ('Operations', 'Operations'), ('Financial Services', 'Financial Services'), ('Information Communication and Technology', 'Information Communication and Technology'), ('Internal Audit', 'Internal Audit'), ('Legal Services and Company Secretariat', 'Legal Services and Company Secretariat'), ('Risk and Compliance', 'Risk and Compliance')], max_length=100, null=True)),
                ('designation', models.CharField(max_length=100, null=True)),
                ('supervisor_name', models.CharField(max_length=100, null=True)),
                ('area_office', models.CharField(choices=[('Gwagwalada', 'Gwagwalada'), ('Jabi', 'Jabi'), ('Kuje', 'Kuje'), ('Apo', 'Apo'), ('Lugbe', 'Lugbe'), ('Lokogoma', 'Lokogoma'), ('Asokoro', 'Asokoro'), ('Garki', 'Garki'), ('Jikwoyi', 'Jikwoyi'), ('Karu', 'Karu'), ('Maitama', 'Maitama'), ('Head Office', 'Head Office'), ('Wuse', 'Wuse'), ('Bwari', 'Bwari'), ('Gwarinpa', 'Gwarinpa'), ('Katampe', 'Katampe'), ('Kubwa', 'Kubwa'), ('Mpape', 'Mpape'), ('Life Camp', 'Life Camp'), ('Bida', 'Bida'), ('Bosso', 'Bosso'), ('Kotangora', 'Kotangora'), ('Minna', 'Minna'), ('Suleja', 'Suleja'), ('Zuma', 'Zuma'), ('Idah', 'Idah'), ('Kabba', 'Kabba'), ('Lokoja', 'Lokoja'), ('Okene', 'Okene'), ('Ado', 'Ado'), ('Akwanga', 'Akwanga'), ('Keffi', 'Keffi'), ('Lafia', 'Lafia'), ('Mararaba', 'Mararaba')], max_length=30, null=True)),
                ('region', models.CharField(choices=[('FCT Central', 'FCT Central'), ('FCT North', 'FCT North'), ('FCT South', 'FCT South'), ('FCT West', 'FCT West'), ('FCT East', 'FCT East'), ('Head Office', 'Head Office'), ('Kogi', 'Kogi'), ('Niger', 'Niger'), ('Nassarawa', 'Nassarawa')], max_length=30, null=True)),
                ('goals_score', models.IntegerField(default=0)),
                ('overall_score_sectA', models.IntegerField(default=0)),
                ('appraisee_email', models.EmailField(max_length=254, null=True)),
                ('appraiser_email', models.EmailField(max_length=254, null=True)),
                ('reviewer_email', models.EmailField(max_length=254, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appraisal_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_from', models.CharField(max_length=50, null=True)),
                ('period_to', models.CharField(max_length=50, null=True)),
                ('goal', models.TextField(max_length=500)),
                ('actual_result', models.TextField(max_length=500)),
                ('weight', models.IntegerField(default=0)),
                ('rating', models.CharField(choices=[(4, 'E'), (3, 'M'), (2, 'PM'), (1, 'DM')], max_length=10)),
                ('score', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Behavioral_competence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_from', models.CharField(max_length=50, null=True)),
                ('period_to', models.CharField(max_length=50, null=True)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('staff_id', models.CharField(max_length=10, null=True)),
                ('job_effectiveness', models.IntegerField(default=0)),
                ('trust_and_integrity', models.IntegerField(default=0)),
                ('supervision', models.IntegerField(default=0)),
                ('dependability', models.IntegerField(default=0)),
                ('collaboration', models.IntegerField(default=0)),
                ('organizational_success', models.IntegerField(default=0)),
                ('customer_orientation', models.IntegerField(default=0)),
                ('leadership_drive', models.IntegerField(default=0)),
                ('compliance_and_safety', models.IntegerField(default=0)),
                ('diversity_and_respect', models.IntegerField(default=0)),
                ('attendance', models.IntegerField(default=0)),
                ('overall_score_sectB', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Overall_rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_from', models.CharField(max_length=50, null=True)),
                ('period_to', models.CharField(max_length=50, null=True)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('staff_id', models.CharField(max_length=10, null=True)),
                ('section_A', models.IntegerField(default=0)),
                ('section_B', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perf_improvement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_from', models.CharField(max_length=50, null=True)),
                ('period_to', models.CharField(max_length=50, null=True)),
                ('key_strength', models.CharField(max_length=50, null=True)),
                ('improvement_area', models.CharField(max_length=50, null=True)),
                ('developmental_recommendation', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
