# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-27 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomplishment',
            name='accomplishment',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='accomplishment',
            name='business_impact',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal_info',
            name='actual_result',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='appraisal_info',
            name='goal',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='perf_improvement',
            name='developmental_recommendation',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='perf_improvement',
            name='improvement_area',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='perf_improvement',
            name='key_strength',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
