# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-27 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0002_auto_20191127_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal_form',
            name='overall_score_sectA',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='behavioral_competence',
            name='overall_score_sectB',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='overall_rating',
            name='section_A',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='overall_rating',
            name='section_B',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='overall_rating',
            name='total_score',
            field=models.FloatField(default=0.0),
        ),
    ]
