# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-02 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0004_auto_20191202_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appraisal_info',
            old_name='rating',
            new_name='appraisee_rating',
        ),
        migrations.AddField(
            model_name='appraisal_form',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='appraisal_form',
            name='goals_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='appraisal_info',
            name='appraiser_rating',
            field=models.CharField(choices=[(4, 'E'), (3, 'M'), (2, 'PM'), (1, 'DM')], max_length=10),
        ),
        migrations.AlterField(
            model_name='appraisal_info',
            name='average',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='appraisal_info',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
