# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-04 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0005_auto_20191202_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appraisal_info',
            name='average',
        ),
        migrations.AlterField(
            model_name='appraisal_form',
            name='total_score',
            field=models.FloatField(default=0.0),
        ),
    ]
