# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-09 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0006_auto_20191204_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal_info',
            name='agreed_rating',
            field=models.CharField(choices=[(4, 'E'), (3, 'M'), (2, 'PM'), (1, 'DM')], default=0, max_length=10),
        ),
    ]
